version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: taskmanager-postgres
    environment:
      POSTGRES_DB: testbase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - taskmanager-net

  redis:
    image: redis:8
    container_name: taskmanager-redis
    ports:
      - "6379:6379"
    networks:
      - taskmanager-net

  app:
    build: .
    container_name: taskmanager-app
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker

      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/testbase
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root

      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
    networks:
      - taskmanager-net


volumes:
  pgdata:

networks:
  taskmanager-net:
