server:
  port: 8080

spring:
  profiles:
    active: docker
  datasource:
    url: jdbc:postgresql://localhost:5432/tm-base
    username: ${DB_USER:postgres}
    password: ${DB_PASS:root}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  data:
    redis:
      timeout: 1s
      connect-timeout: 5s
logging:
  file:
    path: logs
  level:
    root: info
#    org:
#      springframework:
#        boot.autoconfigure: ERROR
#        jdbc: DEBUG
#      hibernate:
#        SQL: DEBUG
#        type.descriptor.sql.BasicBinder: TRACE

debug: true

jwt:
  secret: ${JWT_SECRET:dev-secret}
  expirationAccessToken: 900000
  expirationRefreshToken: 604800000

