spring:
  sql:
    init:
      mode: never
  jpa:
    defer-datasource-initialization: false
  datasource:
    url: jdbc:postgresql://postgres:5432/tm-base
    username: ${DB_USER:postgres}
    password: ${DB_PASS:root}
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: redis
      port: 6379
  flyway:
    enabled: true
    locations: classpath:db/migration